name: eatsgo-platform

services:
  mysql:
    image: eatsgo-mysql:8.0
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: eatsgo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123456
    ports:
      - "3308:3306"
    volumes:
      - eatsgo_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - eatsgo_network

  redis:
    image: redis:7-alpine
    container_name: eatsgo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - eatsgo_network

volumes:
  eatsgo_mysql_data:

networks:
  eatsgo_network:
    driver: bridge

