sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3308
    # port: 3306
    database: sky_take_out
    username: root
    password: root123456
    # password: 8729


  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name: ai-platform666